// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { Terrain as __Terrain } from "./terrain_type";
import { Unit as __Unit } from "./unit_type";
import { Underlay as __Underlay } from "./underlay_type";
import { Overlay as __Overlay } from "./overlay_type";
import type {
  CallReducerFlags,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  ReducerEventContextInterface,
  SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

export type GameState = {
  terrains: __Terrain[],
  units: __Unit[],
  underlays: __Underlay[],
  overlays: __Overlay[],
};

/**
 * A namespace for generated helper functions.
 */
export namespace GameState {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("terrains", AlgebraicType.createArrayType(__Terrain.getTypeScriptAlgebraicType())),
      new ProductTypeElement("units", AlgebraicType.createArrayType(__Unit.getTypeScriptAlgebraicType())),
      new ProductTypeElement("underlays", AlgebraicType.createArrayType(__Underlay.getTypeScriptAlgebraicType())),
      new ProductTypeElement("overlays", AlgebraicType.createArrayType(__Overlay.getTypeScriptAlgebraicType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: GameState): void {
    GameState.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): GameState {
    return GameState.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


