// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

import type {
  CallReducerFlags,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  ReducerEventContextInterface,
  SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

// Import and reexport all reducer arg types
import { AddTerrain } from "./add_terrain_reducer.ts";
export { AddTerrain };
import { AddUnit } from "./add_unit_reducer.ts";
export { AddUnit };
import { IdentityConnected } from "./identity_connected_reducer.ts";
export { IdentityConnected };
import { IdentityDisconnected } from "./identity_disconnected_reducer.ts";
export { IdentityDisconnected };
import { MoveUnit } from "./move_unit_reducer.ts";
export { MoveUnit };

// Import and reexport all table handle types
import { TerrainTableHandle } from "./terrain_table.ts";
export { TerrainTableHandle };
import { UnitTableHandle } from "./unit_table.ts";
export { UnitTableHandle };

// Import and reexport all types
import { Terrain } from "./terrain_type.ts";
export { Terrain };
import { Unit } from "./unit_type.ts";
export { Unit };

const REMOTE_MODULE = {
  tables: {
    terrain: {
      tableName: "terrain",
      rowType: Terrain.getTypeScriptAlgebraicType(),
      primaryKey: "id",
    },
    unit: {
      tableName: "unit",
      rowType: Unit.getTypeScriptAlgebraicType(),
      primaryKey: "id",
    },
  },
  reducers: {
    add_terrain: {
      reducerName: "add_terrain",
      argsType: AddTerrain.getTypeScriptAlgebraicType(),
    },
    add_unit: {
      reducerName: "add_unit",
      argsType: AddUnit.getTypeScriptAlgebraicType(),
    },
    identity_connected: {
      reducerName: "identity_connected",
      argsType: IdentityConnected.getTypeScriptAlgebraicType(),
    },
    identity_disconnected: {
      reducerName: "identity_disconnected",
      argsType: IdentityDisconnected.getTypeScriptAlgebraicType(),
    },
    move_unit: {
      reducerName: "move_unit",
      argsType: MoveUnit.getTypeScriptAlgebraicType(),
    },
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: DbConnectionImpl, event: Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "AddTerrain", args: AddTerrain }
| { name: "AddUnit", args: AddUnit }
| { name: "IdentityConnected", args: IdentityConnected }
| { name: "IdentityDisconnected", args: IdentityDisconnected }
| { name: "MoveUnit", args: MoveUnit }
;

export class RemoteReducers {
  constructor(private connection: DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  addTerrain(terrainId: bigint, newX: number, newY: number, length: number, height: number) {
    const __args = { terrainId, newX, newY, length, height };
    let __writer = new BinaryWriter(1024);
    AddTerrain.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("add_terrain", __argsBuffer, this.setCallReducerFlags.addTerrainFlags);
  }

  onAddTerrain(callback: (ctx: ReducerEventContext, terrainId: bigint, newX: number, newY: number, length: number, height: number) => void) {
    this.connection.onReducer("add_terrain", callback);
  }

  removeOnAddTerrain(callback: (ctx: ReducerEventContext, terrainId: bigint, newX: number, newY: number, length: number, height: number) => void) {
    this.connection.offReducer("add_terrain", callback);
  }

  addUnit(unitId: bigint, newX: number, newY: number, size: number, color: string) {
    const __args = { unitId, newX, newY, size, color };
    let __writer = new BinaryWriter(1024);
    AddUnit.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("add_unit", __argsBuffer, this.setCallReducerFlags.addUnitFlags);
  }

  onAddUnit(callback: (ctx: ReducerEventContext, unitId: bigint, newX: number, newY: number, size: number, color: string) => void) {
    this.connection.onReducer("add_unit", callback);
  }

  removeOnAddUnit(callback: (ctx: ReducerEventContext, unitId: bigint, newX: number, newY: number, size: number, color: string) => void) {
    this.connection.offReducer("add_unit", callback);
  }

  onIdentityConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_connected", callback);
  }

  removeOnIdentityConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_connected", callback);
  }

  onIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_disconnected", callback);
  }

  removeOnIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_disconnected", callback);
  }

  moveUnit(unitId: bigint, newX: number, newY: number) {
    const __args = { unitId, newX, newY };
    let __writer = new BinaryWriter(1024);
    MoveUnit.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("move_unit", __argsBuffer, this.setCallReducerFlags.moveUnitFlags);
  }

  onMoveUnit(callback: (ctx: ReducerEventContext, unitId: bigint, newX: number, newY: number) => void) {
    this.connection.onReducer("move_unit", callback);
  }

  removeOnMoveUnit(callback: (ctx: ReducerEventContext, unitId: bigint, newX: number, newY: number) => void) {
    this.connection.offReducer("move_unit", callback);
  }

}

export class SetReducerFlags {
  addTerrainFlags: CallReducerFlags = 'FullUpdate';
  addTerrain(flags: CallReducerFlags) {
    this.addTerrainFlags = flags;
  }

  addUnitFlags: CallReducerFlags = 'FullUpdate';
  addUnit(flags: CallReducerFlags) {
    this.addUnitFlags = flags;
  }

  moveUnitFlags: CallReducerFlags = 'FullUpdate';
  moveUnit(flags: CallReducerFlags) {
    this.moveUnitFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: DbConnectionImpl) {}

  get terrain(): TerrainTableHandle {
    return new TerrainTableHandle(this.connection.clientCache.getOrCreateTable<Terrain>(REMOTE_MODULE.tables.terrain));
  }

  get unit(): UnitTableHandle {
    return new UnitTableHandle(this.connection.clientCache.getOrCreateTable<Unit>(REMOTE_MODULE.tables.unit));
  }
}

export class SubscriptionBuilder extends SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
