// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

import type {
  CallReducerFlags,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  ReducerEventContextInterface,
  SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type SelectedUnit = {
  id: bigint,
  gameId: bigint,
  startX: number,
  startY: number,
  offsetX: number,
  offsetY: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace SelectedUnit {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU64Type()),
      new ProductTypeElement("gameId", AlgebraicType.createU64Type()),
      new ProductTypeElement("startX", AlgebraicType.createU32Type()),
      new ProductTypeElement("startY", AlgebraicType.createU32Type()),
      new ProductTypeElement("offsetX", AlgebraicType.createU32Type()),
      new ProductTypeElement("offsetY", AlgebraicType.createU32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: SelectedUnit): void {
    SelectedUnit.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): SelectedUnit {
    return SelectedUnit.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


